filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /mnt/logs/*.log
  json:
    message_key: message
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 3
name: filebeat_to_logstash
setup.kibana:
output.logstash:
  hosts: ["logstash:5044"]
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
logging.level: debug
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]
