filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /mnt/logs/*.json
  json.keys_under_root: true
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 3
name: filebeat_to_elasticsearch_2
setup.template.name: "filebeat_elasticsearch-%{[beat.version]}"
setup.template.pattern: "filebeat_elasticsearch-%{[beat.version]}-*"
setup.kibana:
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "filebeat_elasticsearch"
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
logging.level: debug
#logging.json: true
xpack.monitoring.enabled: true
#xpack.monitoring.elasticsearch:
